### PR TITLE
Updates the software FY21 plan, LT plan, and SAT actions

### PR DESCRIPTION
**Pull request by jlaura**
Updated for FY21.

### CODE REVIEW

**Review by rfergason — APPROVED** [review]
I noted some misspellings in the document, but I am certain I did not find them all.  I recommend running a spell check to help find and correct any remaining misspelled words.

FY20 Roadmap
In the year-end summary section, the following changes are needed:
Change FY to FY20
Change the word "he" to "the"
Everything else looked really good.  After the above corrections are made, I think this document is ready to merge.
-----
Roadmap 2021
Note:  In my review, I did not check the content of the roadmap with other ASC task documents to ensure that all relevant tasks are included.  I can do that extra step, if needed.  Let me know.

In the first paragraph, it would be helpful to add the dates that bound the federal fiscal year.  Other sectors of our community might not be familiar.  So, change "The themes and associated tasks are ASC funded work to be completed during FY21." to "The themes and associated tasks are ASC funded work to be completed during FY21 (October 1, 2020 - September 30, 2021)."  You include these dates under the "Themes" section.  Include in both places, as the reader may skip around in the document?  Include at first use (which assumes the reader will read the document from start to finish, which is not a great assumption in this case)?  I think including the date that bounds the fiscal year in both places would be safest, but it is redundant.

Under "ISIS Modularization" we list the task Extraction of PVL and BLOB cabilities from ISIS into standalone libraries.  1) Capabilities needs to be spelled correctly. 2) So that this document is friendly to all levels of users (and developers?), an extra sentence describing what the PVL and BLOB capabilities relate to (metadata, but more specific) is needed.  I think that would help make this document more approachable to our wide user-base.

Community Growth and Support - for the "Improve docuemntation for external contributions" correct the spelling of documentation.

This is nit-picky, but some phrases have periods after them and some do not, and that inconsistent formatting bothers me.  Consider modifying this formatting to be consistent, either by adding periods throughout, or by making all statements either complete sentences or phrases and using punctuation appropriately.

In the summary, a more balanced description of how we support all of our users is needed.  There is a large emphasis on supporting external developers (which is important - can we just call them developers, or is it too soon for that?), but the difference in emphasis I think diminishes the significant support we provide to users - those that generate products, mission teams, and scientists - and could cause feelings of exclusion which is the opposite of the environment I know we are all working to foster.
-----
LongTermPlanning
You did not include the task leads for any of these efforts.  I'm assuming that was intentional, but I don't understand why you left it out. 

Objective 1 - Again, I think it would make this document more approachable to our wide-user base if very technical terms (in this case, PVL and BLOB and how they are used in our software) are defined.

Objective 1 - there is a big emphasis on building and supporting the external development community.  I agree that it is important.  But the term "external" development community could suggest that we are not as interested in supporting our internal development community.  What would be the consequence of simply calling it the "development community"?  See my similar comment above for more context.  On the other hand (sorry, I'm seeing both perspectives and am conflicted), Objective 1 is explicitly describing supporting our Open Source community.  So, in this specific instance, external developers is more appropriate.  We are also growing a community of internal developers as well, however.  You can sigh now at this very non-actionable comment.
 
Objective 2 introduction needs to be more inclusive.  This is entirely focused on our developer user base, and does not mention all the other users, such as processors, mission teams generating processing pipelines, and scientists - just as examples.  I think we need to ensure that we are drafting documents that are inclusive of all of our users.  I think we can also include tasks like improving documentation, improving our control network tool capabilities, adding PDS4 capabilities, etc. as ways we are effectively supporting our broader community.  I think we do ourselves a dis-service by not including all the ways we are working to improve the user experience.  Yes, this will be a long list, but I see no downside to having a long list of ways we are trying to improve the user experience.

Objective 3 - same PVL and BLOB comment as above.  I think making this change throughout would be great, and so I will not keep repeating myself.

Generalize the following statement "Work as members of the support community to address mission issues as they are reported to our software projects." to be more generally - we support our entire user community.

Objective 5:  "Contract NASA Ames to implement these same camera models"  I was surprised to see you use the term "camera model" rather than "sensor model".  Was that intentional?  If not, then being consistent with the more general sensor model would likely reduce confusion.  And I like consistency.

Objective 6:  Capitalization is not consistent with other bullets, or within this item for "Operationalize FY 20 Quantitative metrics for control network"
-----
SAT Review - I don't have any comments.  Changes look good!

**Comment by rfergason** [comment]
I'm still learning the formatting commands in Markdown.  The big, bold letters in my review do not have any special significance.  I was trying to separate my comments for the different sections so that my transition to a new document was obvious, and I used dashes without realizing that I was introducing special formatting.  I apologize for any confusion.

**Comment by jlaura** [comment]
@rfergason I have updates to the files. I need to show you how to do an inline review next time. I think you will find it easier to comment that way.

On the objectives - they are copied directly from the Long Term Plan. I did not write these, I simply copied them from FY20, so I do not believe I have the authority to change them. Having said that. I did make the alteration in number 5 re: camera model because that is largely trivial.

I am going to disagree about Objective 2. The text starts:

> The ASC will build, support, and integrate with the infrastructure necessary for users to install our software with a minimum amount of effort.

This is anyone that want so to install the software. In general, that is everyone except developers who are likely to want to build it locally. The release cadence is also 100% external user focused. 

> The ASC will also release software at a cadence selected to support the largest possible subset of the community.

Devs can run bleeding edge or anything else because they are building locally. Releases are for users. Finally, 

> Additionally, ASC will seek to improve the user experience by, when possible, reducing the total volume of data necessary to store locally and improving the overall performance (speed) of the code base.

is all about the fact that the kernels in the ISIS data area are big and can be a pain to download, store, version, etc. My perspective on Objective 2 is all about getting the code to the user in an easily installable package that runs with a reasonable (and hopefully improving) performance. The projects enumerated in your comment, I think, are more appropriate under objective 4 where we are planning for past, current, and *future* missions. This is where I see us including these enhancement projects.

**Comment by rfergason** [comment]
Comments on your comments:
" I need to show you how to do an inline review next time. I think you will find it easier to comment that way."  Yep. I think you'll find it easier too.  When one only does this a couple times a year and her notes are crappy...  And I'm sorry my ignorance an us being 100% virtual makes this harder and less efficient.

"On the objectives - they are copied directly from the Long Term Plan. I did not write these, I simply copied them from FY20, so I do not believe I have the authority to change them. Having said that. I did make the alteration in number 5 re: camera model because that is largely trivial."  I think I wrote those with your and others input, and thus I thereby formally transfer/share with authority to the Software Lead to change any text he deems appropriate in the Software LTP or any other management documents related to software.  :)

Regarding my statement on Objective 2, I think I see your perspective and I hope my waffling clearly described that I was conflicted in how this should be addressed.  Objective 2 directly supports our external developer community, and I can agree that the focus of those tasks and the descriptive text should also be external developer focused.

Anything else?

**Comment by jlaura** [comment]
@rfergason I updated this after our conversation. Two options - if you think this is good, we can merge and then PR in any changes you would like to see or we can iterate more. 

If we do iterate more, if you click `Files changed` at the top, you can then see the changes (deletions on the left in red and additions on the right in green). You can click on either side (a blue plus box appears) and add comments inline. Just make sure to click 'start a review' and then 'submit review' so that it posts.

**Comment by rfergason** [comment]
Merged changes.  We may iterate more, but I can do a new PR if needed.

**Pull request merged**
